# Primary multilingual speech datasets
mix:
  # ---- ASR (real) ----
  - name: common_voice_17_0
    subset: zh-TW
    split: train
    lang: zh-TW
    hours: 150
    weight: 0.45
    type: asr

  - name: librispeech
    split: train-clean-100
    lang: en
    hours: 100
    weight: 0.25
    type: asr

  # ---- TTS (real) ----
  - name: AISHELL-3
    split: train
    lang: zh
    hours: 30
    weight: 0.12
    type: tts

  - name: VCTK
    split: train
    lang: en
    hours: 30
    weight: 0.08
    type: tts

  # ---- Duplex / Overlap 合成 ----
  - name: duplex_synth_zh
    split: train
    lang: zh
    hours: 30
    weight: 0.08
    type: duplex
    label: barge_in

  - name: duplex_synth_en
    split: train
    lang: en
    hours: 10
    weight: 0.02
    type: duplex
    label: barge_in

synthetic_tts:
  - name: cosyvoice2_cosy_zh
    lang: zh
    items: 200000
    weight: 0.20
    provider: cosyvoice2
    metadata: data/synthetic/cosyvoice2_zh/metadata.json
  - name: cosyvoice2_cosy_en
    lang: en
    items: 150000
    weight: 0.15
    provider: cosyvoice2
    metadata: data/synthetic/cosyvoice2_en/metadata.json

noise:
  - name: musan
    type: noise
  - name: rirs_noises
    type: reverb
  - name: dns_challenge
    type: noise

validation_sets:
  - name: common_voice_17_0
    subset: zh-TW
    split: validation
    lang: zh-TW
  - name: librispeech
    split: dev-clean
    lang: en

manifest_schema:
  path: str
  text: str
  lang: str
  speaker_id: str
  duration: float
  dataset: str
  split: str
  type: str
  label: optional[str]
