# Stage 3: Audio decoder (token -> waveform)
seed: 44
precision: fp16
train_steps: 200000
save_interval: 5000
log_interval: 100
validation_interval: 2000

model:
  type: nar_transformer
  d_model: 896
  num_layers: 18
  num_heads: 8
  ffn_dim: 3584
  dropout: 0.1
  codebooks: 4
  codes_per_book: 8192
  chunk_tokens: 200

optimizer:
  name: adamw
  lr: 0.0002
  betas: [0.9, 0.98]
  weight_decay: 0.01
  warmup_steps: 2000
  scheduler: cosine

batching:
  batch_size: 128
  gradient_accumulation: 4
  dataloader_num_workers: 8

augmentation:
  spec_augment: 0.1
  noise_mix_prob: 0.1

loss:
  objectives:
    - name: code_ce
      weight: 0.7
    - name: mel_l1
      weight: 0.2
    - name: stft_mag
      weight: 0.1

validation_metrics:
  - stoi
  - pesq
  - dnsmos
